import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css"
import SideNav from "../Components/SideNav/NavTabs";
import Footer from "../Components/Footer";
import TopBar from "../Components/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="horizontalCont" >
          <SideNav />
          <div style={{ width: "100%" }}>
            <TopBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
